### ISSUE TITLE
Add a README.md file

### ISSUE THREAD

**Issue by fxbenard** [WP-Translations/wpt-custom-mo-file#16]
Let‘s improve GitHub repo with a nice README.md file with all info related to the plugin.

**Comment by pedro-mendonca** [comment]
Should we add some badges for versions, rating, CI results, etc?

**Comment by fxbenard** [comment]
Yes of course

**Comment by pedro-mendonca** [comment]
The link https://wp-translations.pro/plugins/wpt-custom-mo-file/ is 404.
