### ISSUE TITLE
Deleting and recreating a rule wrongly increment the .mo file

### ISSUE THREAD

**Issue by fxbenard** [WP-Translations/wpt-custom-mo-file#4]
To reproduce:

1. Create a rule txtdomain > /srv/www/../wp-content/uploads/wpt-custom-mo-file/txtdomain-fr_FR.mo
2. Erase it
3. Create it again > /srv/www/../wp-content/uploads/wpt-custom-mo-file/txtdomain-fr_FR-1.mo

The translation doesn't work

**Comment by fxbenard** [comment]
My bad, adding a .mo file from the uploads repo created it. Not really a bug.

**Comment by G3ronim0** [comment]
Yeah wp_handle_upload increment filename when find same filename in upload dir. "Delete rule" button delete file and update database, we still have a problem if user don't delete rule for a theme. Ex : create rule for theme (a) = fr_FR.mo and add new theme and create a new rule for theme (b) without delete the first one = fr_FR-1.mo. Need test...
