### ISSUE TITLE
If the language file is in the original plugin, the override doesn't work

### ISSUE THREAD

**Issue by fxbenard** [WP-Translations/wpt-custom-mo-file#5]
To reproduce:

- Plugin A with translations in plugins > A > languages > A.mo
- wpt-custom created for A > uploads ..

No override

-Remove A.mo from plugins > Override works

**Comment by fxbenard** [comment]
Same if original .mo file is in wp-content > languages > plugins

**Comment by G3ronim0** [comment]
Ok i change method to overwrite text domains, exit override_load_textdomain and welcome to the pair : unload_textdomain and load_textdomain. It's works with 5 text domains... need more tests before closing.
