### ISSUE TITLE
Add custom footer

### ISSUE THREAD

**Issue by fxbenard** [WP-Translations/wpt-custom-mo-file#7]
To keep our UI clean and sober we could add a custom footer in the plugin page to reach out the support page, leave a review, translate and changelog.

E.g from FakerPress:
![2016-08-29_17-19-09](https://cloud.githubusercontent.com/assets/802114/18056593/bf46b3ac-6e0c-11e6-8885-29b6b7050c40.png)

**Comment by G3ronim0** [comment]
Done ! TODO changelog

**Comment by fxbenard** [comment]
First thing tomorrow
